title: QuantEcon
description: QuantEcon is an organization run by economists for economists with the aim of coordinating distributed development of high quality open source code for all forms of quantitative economic modeling
keywords: QuantEcon, Quantitative Economics, Economics, Sloan, Alfred P. Sloan Foundation, Tom J. Sargent, John Stachurski

timezone: Australia/Sydney
google_analytics: G-609ZCT25LS

# baseurl: /quantecon-jekyll-theme/
baseurl: /

sass:
   sass_dir: /assets/sass
   style: :compressed

repository: 

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/bundle

collections:
  news:
  lectures:
  projects:
  team-members:
    people: true

defaults:
  -
    scope:
      type: "lectures"
    values:
      order: 99
    scope:
      type: "projects"
    values:
      order: 99
    scope:
      path: ""
    values:
      layout: 'default'
  
plugins:
  - jekyll-redirect-from